// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/leafy-logos/LogoPreview.tsx": () => import("../components/mockups/leafy-logos/LogoPreview.tsx"),
  "./components/mockups/leafy-variants/NotteVerde.tsx": () => import("../components/mockups/leafy-variants/NotteVerde.tsx"),
  "./components/mockups/leafy-variants/Oceano.tsx": () => import("../components/mockups/leafy-variants/Oceano.tsx")
};
